name: Deploy Website

on:
    push:
        branches: [ main ]


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Sync Website to S3
              run: |
                aws s3 sync ./website s3://cloudpipe-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }} \
                    --delete
            
            - name: Deployment Success
              run: echo "✅ Deployment to S3 successful!"

            